#------ PORT PHYSICAL ------#
scanmap   : 0
disable_oc: 0

#------ PORT PHYSICAL ------#
port_board   : stibase_rtc # shiv34 
port_motor   : stibase_motor
port_imu     : stibase_imu
port_camera  : /017322071534
port_lms100  : 192.168.10.10
port_tim551  : 192.168.100.100
port_ipClient: 10.10.2.9
card_wifi    : wlp3s0

#------ File launch Path------#
#- 1 -
path_firstWork    : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/kickoff/firstWork.launch # clean log.
#- 2 -
path_checkPort    : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/kickoff/checkPhysical.launch
#- 3 -
path_reconnectAll : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/kickoff/reconnect.launch
#- 4 -
path_board        : /home/amr1-l300/catkin_ws/src/ros_canBus/launch/BOARD_RTC.launch
#- 5 -
path_convertCAN   : /home/amr1-l300/catkin_ws/src/ros_canBus/launch/convertCAN_ROS.launch
#- 6 -
path_motor        : /home/amr1-l300/catkin_ws/src/mecanum_pkg/launch/connectCAN.launch
#- 7 -
path_driver       : /home/amr1-l300/catkin_ws/src/mecanum_pkg/launch/controlDriver.launch
#- 8 -
path_kinematic    : /home/amr1-l300/catkin_ws/src/mecanum_pkg/launch/kinematic_mecanum.launch
#- 9 -
path_imu          : /home/amr1-l300/catkin_ws/src/ros_imu_bno055/launch/imu.launch
#- 10 -
path_imuFilter    : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/imu/imuBno_filter.launch
#- 11 -
path_tf           : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/tf/tf_full.launch
#- 12 -
path_camera       : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/camera/D435.launch
#- 13 -
path_lidar        : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/lidar/lidar_full.launch
# -
path_odomEncoder  : /home/amr1-l300/catkin_ws/src/odom_pkg/launch/odom_encoder.launch
path_odomHector   : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/lidar/hector_mapping/hector_odom_v3.launch
path_poseLidar    : /home/amr1-l300/catkin_ws/src/odom_pkg/launch/pose_lidar.launch
# -- 
path_ekf          : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/ekf/ekf.launch
path_mapServer    : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/2DLandmark/map_server.launch
path_amcl         : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/2DLandmark/amcl_v2.launch
# --
path_posePublisher: /home/amr1-l300/catkin_ws/src/pose_publisher/launch/robot_pose.launch

# -- Setpose
path_setPose      : /home/amr1-l300/catkin_ws/src/sti_module/launch/poseRobotTag.launch
# -- Parking
path_parking      : /home/amr1-l300/catkin_ws/src/sti_module/launch/parkingControl.launch
path_apriltag     : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/aruco/launch_apriltag.launch
# -
path_safetyZone   : /home/amr1-l300/catkin_ws/src/safety_zone/launch/safety_zone.launch
# -- 
path_navigation   : /home/amr1-l300/catkin_ws/src/sti_module/launch/goalControl.launch
path_webconsole   : /home/amr1-l300/catkin_ws/src/sti_webconsole/launch/sti_webconsole.launch
path_client       : /home/amr1-l300/catkin_ws/src/sti_control/launch/stiClient.launch
path_control      : /home/amr1-l300/catkin_ws/src/sti_control/launch/stiControl.launch
path_debug        : /home/amr1-l300/catkin_ws/src/sti_control/launch/stiDebug.launch

# -- khong bat luon.
path_checkShelves : /home/amr1-l300/catkin_ws/src/check_shelves/launch/check_shelves.launch # check ke

# -- Detect Tag
path_tagSetpose   : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/aruco/apriltag_d435_setpose.launch
path_tagParking   : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/aruco/apriltag_d435_parking.launch
path_zone3d       : /home/amr1-l300/catkin_ws/src/safe_pcl/launch/zone3d.launch

path_cartographer : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/cartogepher/cartographer.launch

# -- 
path_ApriAddAruco : /home/amr1-l300/catkin_ws/src/launch_pkg/launch/aruco/apriltag_d435_addPoseAruco.launch

# -- add Pose Aruco
path_savePoseAruco: /home/amr1-l300/catkin_ws/src/sti_module/launch/getPoseTag.launch

#------ Time check lost connect ------#
timeLost_board  : 2
timeLost_motor  : 1
timeLost_imu    : 1
timeLost_camera : 2
timeLost_lidar  : 2
timeLost_parking: 4

#------ Time wait after connect ------#
timeWait_board  : 10
timeWait_motr   : 10
timeWait_imu    : 10
timeWait_camera : 10
timeWait_lidar  : 10
timeWait_parking: 10
